{% set name = "pyphen" %}

{% set version = "0.17.0" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d13acd1ce37a384d7612954ae6c7801bb4c5316da0e2b937b2127ba702a3da4


build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python {{ python_min }}

  run:
    - python >={{ python_min }}

test:
  imports:
    - pyphen
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://pyphen.org/
  license: GPL-2.0-or-later AND LGPL-2.1-or-later AND MPL-1.1
  license_file:
    - LICENSE
    - COPYING.GPL
    - COPYING.LGPL
    - COPYING.MPL
  summary: Pure Python module to hyphenate text
  description: |
    Pyphen is a pure Python module to hyphenate text using existing Hunspell
    hyphenation dictionaries.
  doc_url: http://pyphen.org/
  dev_url: https://github.com/Kozea/Pyphen

extra:
  recipe-maintainers:
    - liZe
    - rmax
    - thewchan
