{% set name = "pyphen" %}

{% set version = "0.14.0" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 596c8b3be1c1a70411ba5f6517d9ccfe3083c758ae2b94a45f2707346d8e66fa


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.7

  run:
    - python >=3.7

test:
  imports:
    - pyphen
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pyphen.org/
  license: GPL-2.0-or-later AND LGPL-2.1-or-later AND MPL-1.1
  license_file:
    - LICENSE
    - COPYING.GPL
    - COPYING.LGPL
    - COPYING.MPL
  summary: Pure Python module to hyphenate text
  description: |
    Pyphen is a pure Python module to hyphenate text using existing Hunspell
    hyphenation dictionaries.
  doc_url: http://pyphen.org/
  dev_url: https://github.com/Kozea/Pyphen

extra:
  recipe-maintainers:
    - liZe
    - rmax
    - thewchan
