{% set name = "Pyphen" %}
{% set version = "0.10.0" %}
{% set sha256sum = "719b21dfb4b04fbc11cc0f6112418535fe35474021120cccfffc43a25fe63128" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

about:
  home: http://pyphen.org/
  license: GPL 2.0+/LGPL 2.1+/MPL 1.1
  license_file: COPYING
  summary: Pure Python module to hyphenate text
  description: |
    Pyphen is a pure Python module to hyphenate text using existing Hunspell
    hyphenation dictionaries.
  doc_url: http://pyphen.org/
  dev_url: https://github.com/Kozea/Pyphen

extra:
  recipe-maintainers:
    - rmax
